hithand:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  # -------------------- Thumb
  thumb0_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Thumb_0
    pid: { p: 100.0, i: 0.01, d: 1 }
  thumb1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Thumb_1
    pid: { p: 100.0, i: 0.01, d: 1 }
  thumb2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Thumb_2
    pid: { p: 100.0, i: 0.01, d: 1 }
  thumb3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Thumb_3
    pid: { p: 100.0, i: 0.01, d: 1 }
  # -------------------- Index
  index0_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Index_0
    pid: { p: 100.0, i: 0.01, d: 1 }
  index1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Index_1
    pid: { p: 100.0, i: 0.01, d: 1 }
  index2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Index_2
    pid: { p: 100.0, i: 0.01, d: 1 }
  index3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Index_3
    pid: { p: 100.0, i: 0.01, d: 1 }
  # -------------------- Middle
  middle0_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Middle_0
    pid: { p: 100.0, i: 0.01, d: 1 }
  middle1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Middle_1
    pid: { p: 100.0, i: 0.01, d: 1 }
  middle2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Middle_2
    pid: { p: 100.0, i: 0.01, d: 1 }
  middle3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Middle_3
    pid: { p: 100.0, i: 0.01, d: 1 }
  # -------------------- Ring
  ring0_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Ring_0
    pid: { p: 100.0, i: 0.01, d: 1 }
  ring1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Ring_1
    pid: { p: 100.0, i: 0.01, d: 1 }
  ring2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Ring_2
    pid: { p: 100.0, i: 0.01, d: 1 }
  ring3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Ring_3
    pid: { p: 100.0, i: 0.01, d: 1 }
  # -------------------- Little
  little0_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Little_0
    pid: { p: 100.0, i: 0.01, d: 1 }
  little1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Little_1
    pid: { p: 100.0, i: 0.01, d: 1 }
  little2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Little_2
    pid: { p: 100.0, i: 0.01, d: 1 }
  little3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Right_Little_3
    pid: { p: 100.0, i: 0.01, d: 1 }
