hithand:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  # position_controllers
  # effort_controllers
  # pid: {p: 500.0, i: 0.01, d: 10.0}
  # pid: {p: 0.0, i: 0.0, d: 0.0}
#  thumb1_position_controller:
#    type: position_controllers/JointPositionController
#    joint: Right_Thumb_1
#    pid:
#      p: 500.0
#      i: 0.01
#      d: 10.0
#
#  thumb2_position_controller:
#    type: position_controllers/JointPositionController
#    joint: Right_Thumb_2
#    pid:
#      p: 500.0
#      i: 0.01
#      d: 10.0
  thumb3_position_controller:
    type: position_controllers/JointPositionController
    joint: Right_Thumb_3
    pid:
      p: 500.0
      i: 0.01
      d: 10.0
#  thumb4_position_controller:
#    type: position_controllers/JointPositionController
#    joint: Right_Thumb_4
#    pid:
#      p: 500.0
#      i: 0.01
#      d: 10.0

#  gazebo_ros_control:
#    pid_gains:
#      Right_Thumb_1: {p: 500.0, i: 0.0, d: 10.0}
#      Right_Thumb_2: {p: 500.0, i: 0.0, d: 10.0}
#      Right_Thumb_3: {p: 500.0, i: 0.0, d: 10.0}
#      Right_Thumb_4: {p: 500.0, i: 0.0, d: 10.0}
# not working for error no p gain specified
#/gazebo_ros_control:
#  pid_gains:
#    Right_Thumb_1:
#      p: 500,0
#      i: 0.01
#      d: 10.0


#gazebo_ros_control:
#  pid_gains:
#    thumb1_position_controller: {p: 10.0, i: 0.1, d: 0.01}
#    Right_Thumb_1: {p: 10.0,i: 0.1, d: 0.01}
#    thumb3_position_controller: {p: 10.0,i: 0.1, d: 0.01}
#    thumb4_position_controller: {p: 10.0,i: 0.1, d: 0.01}

#  # -------------------- Index
#  index1_position_controller:
#    type: JointPositionController
#    joint: Right_Index_1
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  index2_position_controller:
#    type: JointPositionController
#    joint: Right_Index_2
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  index3_position_controller:
#    type: JointPositionController
#    joint: Right_Index_3
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  index4_position_controller:
#    type: JointPositionController
#    joint: Right_Index_4
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#
#  middle1_position_controller:
#    type: JointPositionController
#    joint: Right_Middle_1
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  middle2_position_controller:
#    type: JointPositionController
#    joint: Right_Middle_2
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  middle3_position_controller:
#    type: JointPositionController
#    joint: Right_Middle_3
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  middle4_position_controller:
#    type: JointPositionController
#    joint: Right_Middle_4
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#
#  ring1_position_controller:
#    type: JointPositionController
#    joint: Right_Ring_1
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  ring2_position_controller:
#    type: JointPositionController
#    joint: Right_Ring_2
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  ring3_position_controller:
#    type: JointPositionController
#    joint: Right_Ring_3
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  ring4_position_controller:
#    type: JointPositionController
#    joint: Right_Ring_4
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#
#  little1_position_controller:
#    type: JointPositionController
#    joint: Right_Little_1
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  little2_position_controller:
#    type: JointPositionController
#    joint: Right_Little_2
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  little3_position_controller:
#    type: JointPositionController
#    joint: Right_Little_3
#    pid: {p: 500.0, i: 0.01, d: 10.0}
#  little4_position_controller:
#    type: JointPositionController
#    joint: Right_Little_4
#    pid: {p: 500.0, i: 0.01, d: 10.0}